/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.vroom.abas;

import java.sql.*;
import br.com.vroom.dal_cad.Principal;
import java.awt.Color;
import javax.swing.JOptionPane;

public class Aba_Login extends javax.swing.JFrame {

    /**
     * Creates new form Aba_Login
     */
    //usando variavel conexao do DAL(CAD)
    Connection conexao = null;
    /*
    PreparedStatement e ResultSet são frameworks do package java.sql
    Eles servem para preparar e executar as instruções SQL
     */
    PreparedStatement pst = null;
    ResultSet rs = null;

    public void logar() {
        String sql = "select * from tabusuarios where login=? and senha=?";
        try {
            //o código abaixa prepara a consulta ao banco em função do que for digitado nas text field
            // (?) é substituido pelo conteúdo das variáveis
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txt_login.getText());
            //]
            String captura_senha = new String(txt_senha.getPassword());
            pst.setString(2, captura_senha);
            // código de execução da query(consulta ao banco de dados)
            rs = pst.executeQuery();
            // usuario && senha válido
            if (rs.next()) {
                // linha abaixo obtem o contéudo do campo perfil na tabusuarios
                String perfil = rs.getString(7);
                //estrutura abaixo faz o tratamento do perfil do usuário
                if (perfil.equals("administrador")) {
                    //linha abaixo exibe o conteúdo do campo da tabela
                    Aba_Principal abaprincipal = new Aba_Principal();
                    abaprincipal.setVisible(true);
                    Aba_Principal.menuUSUARIOS.setEnabled(true);
                    Aba_Principal.MI_E_GERENCIAR.setEnabled(true);
                    Aba_Principal.MI_C_GERENCIAR.setEnabled(true);
                    Aba_Principal.menuRELATORIO.setEnabled(true);
                    Aba_Principal.menu_A_VeiculosAlocados.setEnabled(true);
                    Aba_Principal.lbl_Usuario.setText(rs.getString(2));
                    Aba_Principal.lbl_perfil.setText(rs.getString(7));
                    Aba_Principal.lbl_perfil.setForeground(Color.red);
                    this.dispose();
                    conexao.close();
                } else {
                    Aba_Principal abaprincipal = new Aba_Principal();
                    abaprincipal.setVisible(true);
                    Aba_Principal.lbl_Usuario.setText(rs.getString(2));
                    Aba_Principal.lbl_perfil.setText(rs.getString(7));
                    this.dispose();
                    conexao.close();
                }
            } else {
                JOptionPane.showMessageDialog(null, "usuário e/ou senha inválido(s)");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha no login, verifique a sua conexão com o Banco de Dados", "ATENÇÃO!", JOptionPane.WARNING_MESSAGE);

        }
    }

    public Aba_Login() {
        initComponents();
        conexao = Principal.conector();
        //código serve de apoio ao status da conexão
        if (conexao != null) {
            lbl_status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vroom/icons/datab_on.png")));
        } else {
            lbl_status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vroom/icons/datab_off.png")));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_login = new javax.swing.JTextField();
        txt_senha = new javax.swing.JPasswordField();
        but_Enter = new javax.swing.JButton();
        bg_abalogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vroom/icons/close_20dp_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vroom/icons/LOGOMARCA22222.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 270, 110));

        lbl_status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vroom/icons/datab_off.png"))); // NOI18N
        getContentPane().add(lbl_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 410, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("LOGIN");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 100));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 110, 40));
        getContentPane().add(txt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 270, 33));
        getContentPane().add(txt_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 270, 33));

        but_Enter.setBackground(new java.awt.Color(51, 0, 153));
        but_Enter.setForeground(new java.awt.Color(255, 255, 255));
        but_Enter.setText("ENTER");
        but_Enter.setBorderPainted(false);
        but_Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_EnterActionPerformed(evt);
            }
        });
        getContentPane().add(but_Enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 80, 30));

        bg_abalogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vroom/icons/Vroom (1).png"))); // NOI18N
        getContentPane().add(bg_abalogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 510));

        setSize(new java.awt.Dimension(919, 515));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void but_EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_EnterActionPerformed
        // usando metodo logar
        logar();
    }//GEN-LAST:event_but_EnterActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aba_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aba_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aba_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aba_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aba_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_abalogin;
    private javax.swing.JButton but_Enter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JTextField txt_login;
    private javax.swing.JPasswordField txt_senha;
    // End of variables declaration//GEN-END:variables
}
