/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.vroom.abas;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 * Classe que representa a janela principal do sistema VROOM. Esta classe é
 * responsável por exibir a interface gráfica principal do sistema. Ela inclui
 * menus para acessar diferentes funcionalidades do sistema. Também exibe
 * informações sobre o usuário logado e a data atual.
 */
public class Aba_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Aba_Principal
     */
    public Aba_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Data = new javax.swing.JLabel();
        Nome_Empresa = new javax.swing.JLabel();
        Nome_Usuario = new javax.swing.JLabel();
        lbl_perfil = new javax.swing.JLabel();
        lbl_Usuario = new javax.swing.JLabel();
        lblBG_Aba_Principal = new javax.swing.JLabel();
        Desktop_Pane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUSUARIOS = new javax.swing.JMenu();
        MI_U_GERENCIAR = new javax.swing.JMenuItem();
        MI_U_CADASTRAR = new javax.swing.JMenuItem();
        menuCLIENTES = new javax.swing.JMenu();
        MI_C_GERENCIAR = new javax.swing.JMenuItem();
        MI_C_CADASTRAR = new javax.swing.JMenuItem();
        menuESTOQUE = new javax.swing.JMenu();
        MI_E_GERENCIAR = new javax.swing.JMenuItem();
        MI_E_CADASTRAR = new javax.swing.JMenuItem();
        menuALOCACAO = new javax.swing.JMenu();
        MI_A_ALOCAR = new javax.swing.JMenuItem();
        menu_A_VeiculosAlocados = new javax.swing.JMenuItem();
        Menu_A_Relatorio = new javax.swing.JMenuItem();
        menuRELATORIO = new javax.swing.JMenu();
        relCLIENTES = new javax.swing.JMenuItem();
        relVEICULOS = new javax.swing.JMenuItem();
        relUSUARIOS = new javax.swing.JMenuItem();
        menuAJUDA = new javax.swing.JMenu();
        MI_AJ_SOBRE = new javax.swing.JMenuItem();
        menuOPCOES = new javax.swing.JMenu();
        MI_O_SAIR = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VROOM system");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Data.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_Data.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Data.setText("data");
        getContentPane().add(lbl_Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 200, 20));

        Nome_Empresa.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Nome_Empresa.setForeground(new java.awt.Color(255, 255, 255));
        Nome_Empresa.setText("VROOM");
        getContentPane().add(Nome_Empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        Nome_Usuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Nome_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Nome_Usuario.setText("USUÁRIO:");
        getContentPane().add(Nome_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        lbl_perfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_perfil.setForeground(new java.awt.Color(0, 51, 255));
        lbl_perfil.setText("profile");
        getContentPane().add(lbl_perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        lbl_Usuario.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        lbl_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Usuario.setText("USUÁRIO");
        getContentPane().add(lbl_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        lblBG_Aba_Principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vroom/icons/fundoabaprincipalpt5.png"))); // NOI18N
        getContentPane().add(lblBG_Aba_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 230, 550));

        Desktop_Pane.setBackground(new java.awt.Color(255, 255, 255));
        Desktop_Pane.setPreferredSize(new java.awt.Dimension(710, 530));
        getContentPane().add(Desktop_Pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 750, -1));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(408, 35));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(408, 35));

        menuUSUARIOS.setText("Usuários");
        menuUSUARIOS.setEnabled(false);

        MI_U_GERENCIAR.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MI_U_GERENCIAR.setText("Gerenciar");
        MI_U_GERENCIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_U_GERENCIARActionPerformed(evt);
            }
        });
        menuUSUARIOS.add(MI_U_GERENCIAR);

        MI_U_CADASTRAR.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MI_U_CADASTRAR.setText("Cadastrar");
        MI_U_CADASTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_U_CADASTRARActionPerformed(evt);
            }
        });
        menuUSUARIOS.add(MI_U_CADASTRAR);

        jMenuBar1.add(menuUSUARIOS);

        menuCLIENTES.setText("Clientes");

        MI_C_GERENCIAR.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MI_C_GERENCIAR.setText("Gerenciar");
        MI_C_GERENCIAR.setEnabled(false);
        MI_C_GERENCIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_C_GERENCIARActionPerformed(evt);
            }
        });
        menuCLIENTES.add(MI_C_GERENCIAR);

        MI_C_CADASTRAR.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MI_C_CADASTRAR.setText("Cadastrar");
        MI_C_CADASTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_C_CADASTRARActionPerformed(evt);
            }
        });
        menuCLIENTES.add(MI_C_CADASTRAR);

        jMenuBar1.add(menuCLIENTES);

        menuESTOQUE.setText("Estoque");

        MI_E_GERENCIAR.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_0, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        MI_E_GERENCIAR.setText("Gerenciar");
        MI_E_GERENCIAR.setEnabled(false);
        MI_E_GERENCIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_E_GERENCIARActionPerformed(evt);
            }
        });
        menuESTOQUE.add(MI_E_GERENCIAR);

        MI_E_CADASTRAR.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        MI_E_CADASTRAR.setText("Cadastrar");
        MI_E_CADASTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_E_CADASTRARActionPerformed(evt);
            }
        });
        menuESTOQUE.add(MI_E_CADASTRAR);

        jMenuBar1.add(menuESTOQUE);

        menuALOCACAO.setText("Alocação");

        MI_A_ALOCAR.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        MI_A_ALOCAR.setText("Alocar");
        MI_A_ALOCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_A_ALOCARActionPerformed(evt);
            }
        });
        menuALOCACAO.add(MI_A_ALOCAR);

        menu_A_VeiculosAlocados.setText("Veículos Alocados");
        menu_A_VeiculosAlocados.setEnabled(false);
        menu_A_VeiculosAlocados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_A_VeiculosAlocadosActionPerformed(evt);
            }
        });
        menuALOCACAO.add(menu_A_VeiculosAlocados);

        Menu_A_Relatorio.setText("Relatório");
        Menu_A_Relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_A_RelatorioActionPerformed(evt);
            }
        });
        menuALOCACAO.add(Menu_A_Relatorio);

        jMenuBar1.add(menuALOCACAO);

        menuRELATORIO.setText("Relatório");
        menuRELATORIO.setEnabled(false);

        relCLIENTES.setText("Clientes");
        relCLIENTES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relCLIENTESActionPerformed(evt);
            }
        });
        menuRELATORIO.add(relCLIENTES);

        relVEICULOS.setText("Veiculos");
        relVEICULOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relVEICULOSActionPerformed(evt);
            }
        });
        menuRELATORIO.add(relVEICULOS);

        relUSUARIOS.setText("Usuarios");
        relUSUARIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relUSUARIOSActionPerformed(evt);
            }
        });
        menuRELATORIO.add(relUSUARIOS);

        jMenuBar1.add(menuRELATORIO);

        menuAJUDA.setText("Ajuda");

        MI_AJ_SOBRE.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MI_AJ_SOBRE.setText("Sobre");
        MI_AJ_SOBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_AJ_SOBREActionPerformed(evt);
            }
        });
        menuAJUDA.add(MI_AJ_SOBRE);

        jMenuBar1.add(menuAJUDA);

        menuOPCOES.setText("Opções");
        menuOPCOES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOPCOESActionPerformed(evt);
            }
        });

        MI_O_SAIR.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MI_O_SAIR.setText("Sair");
        MI_O_SAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_O_SAIRActionPerformed(evt);
            }
        });
        menuOPCOES.add(MI_O_SAIR);

        jMenuBar1.add(menuOPCOES);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(995, 569));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
     * Método responsável por executar a ação quando o item de menu "Gerenciar"
     * de usuários é selecionado. Ele cria uma nova instância da classe
     * Aba_Gerenciar_USUARIOS e a exibe.
     *
     * @param evt O evento de ação que desencadeou esta ação.
     */
    private void MI_E_GERENCIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_E_GERENCIARActionPerformed
        Aba_Gerenciar_ESTOQUE abagerenciarE = new Aba_Gerenciar_ESTOQUE();
        abagerenciarE.setVisible(true);
        Desktop_Pane.add(abagerenciarE);
    }//GEN-LAST:event_MI_E_GERENCIARActionPerformed

    /**
     * Método responsável por executar a ação quando a janela é ativada. Ele
     * atualiza o texto da label lbl_Data com a data atual.
     *
     * @param evt O evento de janela que desencadeou esta ação.
     */
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // colocanco a data na lbl_data (na página principal do sistema)
        Date data = new Date();
        DateFormat format = DateFormat.getDateInstance(DateFormat.SHORT);
        lbl_Data.setText(format.format(data));

    }//GEN-LAST:event_formWindowActivated

    private void menuOPCOESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOPCOESActionPerformed

    }//GEN-LAST:event_menuOPCOESActionPerformed
    /**
     * Método responsável por executar a ação quando o item de menu "Sair" é
     * selecionado. Ele exibe uma caixa de diálogo para confirmar a saída do
     * sistema e, se confirmado, fecha o sistema.
     *
     * @param evt O evento de ação que desencadeou esta ação.
     */
    private void MI_O_SAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_O_SAIRActionPerformed
        //caixa para confirmar a saída do sistema
        int exit = JOptionPane.showConfirmDialog(null, "Tem certeza que desea sair?", "ATENÇÃO!", JOptionPane.YES_NO_OPTION);
        if (exit == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_MI_O_SAIRActionPerformed

    /**
     * Método responsável por executar a ação quando o item de menu "Sobre" é
     * selecionado. Ele cria uma nova instância da classe Aba_Sobre e a exibe.
     *
     * @param evt O evento de ação que desencadeou esta ação.
     */
    private void MI_AJ_SOBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_AJ_SOBREActionPerformed
        // caixa sobre o programa
        Aba_Sobre sobre = new Aba_Sobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_MI_AJ_SOBREActionPerformed

    /**
     * Método responsável por executar a ação quando o item de menu "Cadastrar"
     * de usuários é selecionado. Ele cria uma nova instância da classe
     * Aba_Cadastrar_USUARIO e a exibe.
     *
     * @param evt O evento de ação que desencadeou esta ação.
     */
    private void MI_U_CADASTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_U_CADASTRARActionPerformed
        // abrindo aba de cadastro do cliente
        Aba_Cadastrar_USUARIO abacadastrarU = new Aba_Cadastrar_USUARIO();
        abacadastrarU.setVisible(true);
        Desktop_Pane.add(abacadastrarU);
    }//GEN-LAST:event_MI_U_CADASTRARActionPerformed

    /**
     * Método responsável por executar a ação quando o item de menu "Cadastrar"
     * de veículos é selecionado. Ele cria uma nova instância da classe
     * Aba_Cadastrar_VEICULO e a exibe.
     *
     * @param evt O evento de ação que desencadeou esta ação.
     */
    private void MI_E_CADASTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_E_CADASTRARActionPerformed
        Aba_Cadastrar_VEICULO abacadastrarE = new Aba_Cadastrar_VEICULO();
        abacadastrarE.setVisible(true);
        Desktop_Pane.add(abacadastrarE);
    }//GEN-LAST:event_MI_E_CADASTRARActionPerformed

    /**
     * Método responsável por executar a ação quando o item de menu "Gerenciar"
     * de usuarios é selecionado. Ele cria uma nova instância da classe
     * Aba_Gerenciar_USUARIOS e a exibe.
     *
     * @param evt O evento de ação que desencadeou esta ação.
     */
    private void MI_U_GERENCIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_U_GERENCIARActionPerformed
        Aba_Gerenciar_USUARIOS abagerenciarU = new Aba_Gerenciar_USUARIOS();
        abagerenciarU.setVisible(true);
        Desktop_Pane.add(abagerenciarU);
    }//GEN-LAST:event_MI_U_GERENCIARActionPerformed

    /**
     * Método responsável por executar a ação quando o item de menu "Gerenciar"
     * de clientes é selecionado. Ele cria uma nova instância da classe
     * Aba_Gerenciar_CLIENTE e a exibe.
     *
     * @param evt O evento de ação que desencadeou esta ação.
     */
    private void MI_C_GERENCIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_C_GERENCIARActionPerformed
        Aba_Gerenciar_CLIENTE abagerenciarC = new Aba_Gerenciar_CLIENTE();
        abagerenciarC.setVisible(true);
        Desktop_Pane.add(abagerenciarC);
    }//GEN-LAST:event_MI_C_GERENCIARActionPerformed

    /**
     * Método responsável por executar a ação quando o item de menu "Alocar" de
     * alocação é selecionado. Ele cria uma nova instância da classe
     * Aba_ALOCAMENTO e a exibe.
     *
     * @param evt O evento de ação que desencadeou esta ação.
     */
    private void MI_A_ALOCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_A_ALOCARActionPerformed
        Aba_ALOCAMENTO abaalocar = new Aba_ALOCAMENTO();
        abaalocar.setVisible(true);
        Desktop_Pane.add(abaalocar);
    }//GEN-LAST:event_MI_A_ALOCARActionPerformed

    /**
     * Método responsável por executar a ação quando o item de menu "Veiculos
     * Alocados" de Alocação é selecionado. Ele cria uma nova instância da
     * classe Aba_A_Relatorio e a exibe.
     *
     * @param evt O evento de ação que desencadeou esta ação.
     */
    private void menu_A_VeiculosAlocadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_A_VeiculosAlocadosActionPerformed
        Aba_Relatório_Alocamentos abarelatorioA = new Aba_Relatório_Alocamentos();
        abarelatorioA.setVisible(true);
        Desktop_Pane.add(abarelatorioA);
    }//GEN-LAST:event_menu_A_VeiculosAlocadosActionPerformed

    /**
     * Método responsável por executar a ação quando o item de menu "Cadastrar"
     * de clientes é selecionado. Ele cria uma nova instância da classe
     * Aba_Cadastrar_CLIENTE e a exibe.
     *
     * @param evt O evento de ação que desencadeou esta ação.
     */
    private void MI_C_CADASTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_C_CADASTRARActionPerformed
        Aba_Cadastrar_CLIENTE abacadastrarC = new Aba_Cadastrar_CLIENTE();
        abacadastrarC.setVisible(true);
        Desktop_Pane.add(abacadastrarC);
    }//GEN-LAST:event_MI_C_CADASTRARActionPerformed

    /**
     * Método responsável por executar a ação quando o item de menu "Clientes"
     * de Relatório é selecionado. Ele cria uma nova instância da classe
     * Aba_Relatorio_CLIENTES e a exibe.
     *
     * @param evt O evento de ação que desencadeou esta ação.
     */
    private void relCLIENTESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relCLIENTESActionPerformed
        Aba_Relatorio_CLIENTES abarelatorioC = new Aba_Relatorio_CLIENTES();
        abarelatorioC.setVisible(true);
        Desktop_Pane.add(abarelatorioC);
    }//GEN-LAST:event_relCLIENTESActionPerformed

    /**
     * Método responsável por executar a ação quando o item de menu "Veículos"
     * de Relatório é selecionado. Ele cria uma nova instância da classe
     * Aba_Relatorio_VEICULOS e a exibe.
     *
     * @param evt O evento de ação que desencadeou esta ação.
     */
    private void relVEICULOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relVEICULOSActionPerformed
        Aba_Relatorio_VEICULOS abarelatorioV = new Aba_Relatorio_VEICULOS();
        abarelatorioV.setVisible(true);
        Desktop_Pane.add(abarelatorioV);
    }//GEN-LAST:event_relVEICULOSActionPerformed
    /**
     * Método responsável por executar a ação quando o item de menu "Usuários"
     * de Relatório é selecionado. Ele cria uma nova instância da classe
     * Aba_Relatorio_USUARIOS e a exibe.
     *
     * @param evt O evento de ação que desencadeou esta ação.
     */
    private void relUSUARIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relUSUARIOSActionPerformed
        Aba_Relatorio_USUARIOS abarelatorioU = new Aba_Relatorio_USUARIOS();
        abarelatorioU.setVisible(true);
        Desktop_Pane.add(abarelatorioU);
    }//GEN-LAST:event_relUSUARIOSActionPerformed

    /**
     * Método responsável por executar a ação quando o item de menu "Relatório"
     * de alocação é selecionado. Ele cria uma nova instância da classe
     * Aba_A_Relatorio e a exibe.
     *
     * @param evt O evento de ação que desencadeou esta ação.
     */
    private void Menu_A_RelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_A_RelatorioActionPerformed
        Aba_A_Relatorio abarelatorioA = new Aba_A_Relatorio();
        abarelatorioA.setVisible(true);
        Desktop_Pane.add(abarelatorioA);
    }//GEN-LAST:event_Menu_A_RelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aba_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aba_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aba_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aba_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aba_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop_Pane;
    private javax.swing.JMenuItem MI_AJ_SOBRE;
    private javax.swing.JMenuItem MI_A_ALOCAR;
    private javax.swing.JMenuItem MI_C_CADASTRAR;
    public static javax.swing.JMenuItem MI_C_GERENCIAR;
    private javax.swing.JMenuItem MI_E_CADASTRAR;
    public static javax.swing.JMenuItem MI_E_GERENCIAR;
    private javax.swing.JMenuItem MI_O_SAIR;
    private javax.swing.JMenuItem MI_U_CADASTRAR;
    private javax.swing.JMenuItem MI_U_GERENCIAR;
    private javax.swing.JMenuItem Menu_A_Relatorio;
    private javax.swing.JLabel Nome_Empresa;
    public static javax.swing.JLabel Nome_Usuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBG_Aba_Principal;
    private javax.swing.JLabel lbl_Data;
    public static javax.swing.JLabel lbl_Usuario;
    public static javax.swing.JLabel lbl_perfil;
    private javax.swing.JMenu menuAJUDA;
    private javax.swing.JMenu menuALOCACAO;
    private javax.swing.JMenu menuCLIENTES;
    private javax.swing.JMenu menuESTOQUE;
    private javax.swing.JMenu menuOPCOES;
    public static javax.swing.JMenu menuRELATORIO;
    public static javax.swing.JMenu menuUSUARIOS;
    public static javax.swing.JMenuItem menu_A_VeiculosAlocados;
    private javax.swing.JMenuItem relCLIENTES;
    private javax.swing.JMenuItem relUSUARIOS;
    private javax.swing.JMenuItem relVEICULOS;
    // End of variables declaration//GEN-END:variables
}
